IF(SELECT DISTINCT DEPTNO FROM DEPT)=10
BEGIN
SELECT DEPTNO,
	CASE
		WHEN DNAME='ACCOUNTING'
			THEN 'ACC'
		WHEN DNAME='RESEARCH'
			THEN 'R&S'
		WHEN DNAME='SALES'
			THEN 'SAL'
		WHEN DNAME='OPERATIONS'
			THEN 'OP'
	END AS DNAME,
	LOC         
  FROM DEPT
END

ELSE
BEGIN
    PRINT 'DEPTNO NOT MATCHING'
END